baseURL = "https://starnishi.github.io/hugodocsy/"
title = "My New Hugo Site"
theme = ["docsy"]
contentDir = "content/ja"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

# Will give values to .Lastmod etc.
# enableGitInfo = true

[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/starnishi/hugodocsy/"

[languages]
[languages.ja]
title = "Docsy"
description = "Docsy does docs"
languageName ="Japanese"
[languages.en]
title = "Docsy"
description = "Docsy does docs"
languageName ="English"

[params]
copyright = "The Docsy Authors"
privacy_policy = "https://policies.google.com/privacy"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/starnishi/hugodocsy"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/starnishi/hugodocsy"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'